title:              Alexander Villasoto
email:              anvillasoto@gmail.com
description:        Web Developer, Data Science Enthusiast
author:             Alexander Villasoto
baseurl:            "/"
url:                "anvillasoto.github.io"

# Social Profiles
twitter_username:   anvillasoto
github_username:    anvillasoto
facebook_username:  anvillasoto
linkedin_username:  anvillasoto

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
